#!/usr/bin/env node
require('@babel/register')({
    presets: [
        [
            '@babel/preset-env',
            {
                targets: {
                    node: 'current',
                },
            },
        ],
    ],
});

const config = require('./config');
const {default: CommandLoader} = require(config.sourcePath + '/Core/Express/CommandLoader');
CommandLoader.load();
