name: Express JS

on:
  push:
    branches: ['**']
  # pull_request:
  #   branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: password       
    #     ports:
    #     - 3366:3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    # - name: Verify MySQL connection from host
    #   run: |
    #     sudo apt-get install -y mysql-client
    #     mysql --host 127.0.0.1 --port 3366 -uroot -ppassword -e "CREATE DATABASE IF NOT EXISTS amanahmarttest; SHOW DATABASES;"

    - name: Install dependencies
      run: yarn install
    
    - name: Run linting for js using eslint
      run: npx eslint --fix src
    
    - name: Run linting for js using eslint
      run: yarn jest src/Test